version: '3.8'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    environment:
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=password
      - MONGO_HOSTNAME=db
      - MONGO_PORT=27017
      - MONGO_DB=vanguard
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - vanguardians
    command: npm run dev
    depends_on:
      - db

  db:
    image: mongo:4.1.8-xenial
    container_name: db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=vanguard
    volumes:
      - dbdata:/data/db
    networks:
      - vanguardians
    ports:
      - '27017:27017'

networks:
  vanguardians:
    driver: bridge

volumes:
  dbdata:
  node_modules:
